### ISSUE TITLE
Create a manifest that can take multiple networks 

### ISSUE THREAD

**Issue by maektwain** [Cynsar-Foundation/second.subgraph#1]
Right now the current stack will deploy on the graph protocol is the one that we will specify, we should build a directory that have 

`manifest/data`

The above directory contains code like this below 

```
{
    "network": "fuji",
    "dataSources": {
      "ContractName": [
        {
          "name": "ContractName",
          "address": "0x7C7fb777A1AecAea52443835a5681a4828F363Fe",
          "startBlock": 4178644
        }
      ]
    }
  }
  
```

The above specified file can be saved for the network type and In build or deployment easily deployed , 

The second part is the template.yaml. for the contracts that we will have ,

like this 

```
# GovernRegistry
- kind: ethereum/contract
  name: {{name}}
  network: {{network}}
  source:
    abi: ContractName
    address: '{{address}}'
    startBlock: {{startBlock}}
  mapping:
    kind: ethereum/events
    apiVersion: 0.0.1
    language: wasm/assemblyscript
    entities:
      - SomeEntry
      - None
    abis:
      - name: This and That
        file: $module/abi/contracts/GovernRegistry.sol/GovernRegistry.json
      - name: GovernQueue
        file: $module/abi/contracts/pipelines/GovernQueue.sol/GovernQueue.json
    eventHandlers:
      - event: Registered(indexed address,address,indexed address,address,indexed address,string)
        handler: handleRegistered
      - event: SetMetadata(indexed address,bytes)
        handler: handleSetMetadata
    file: ./src/this.js

```
